class Client {
    public static void main(String[] args) {
        Media media = new Media();

        media.play();   // Starting...
        media.pause();  // Pausing...
        media.play();   // Resuming...
        media.stop();   // Stopping...
        media.pause();  // Cannot pause. Media is stopped.
        media.play();   // Starting...
    }
}
